name: CI/CD

on:
  push:
    branches:
      - deployment
    paths:
      - 'server/**'
      - 'client/**'

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ secrets.ECR_URL }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.ECR_REGION }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.ECR_URL }}/nodejs-app ./server
      - name: Push Image to Amazon ECR
        run: docker push ${{ secrets.ECR_URL }}/nodejs-app:latest

  deploy_backend:
    needs: build_backend
    runs-on: self-hosted
    steps:
      - name: Pull image from Amazon ECR
        run: docker pull ${{ secrets.ECR_URL }}/nodejs-app:latest 
      - name: Delete old container
        run: docker rm -f nodejs-app-container  
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name nodejs-app-container -e MONGODB_URI='${{ secrets.MONGODB_URI }}' ${{ secrets.ECR_URL }}/nodejs-app

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ secrets.ECR_URL }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.ECR_REGION }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.ECR_URL }}/reactjs-app --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL }}' ./client
      - name: Push Image to Amazon ECR
        run: docker push ${{ secrets.ECR_URL }}/reactjs-app:latest

  deploy_frontend:
    needs: build_frontend
    runs-on: self-hosted 
    steps:
      - name: Pull image from Amazon ECR
        run: docker pull ${{ secrets.ECR_URL }}/reactjs-app:latest 
      - name: Delete old container
        run: docker rm -f reactjs-app-container
      - name: Run Docker Container
        run: docker run -d -p 80:80 --name reactjs-app-container ${{ secrets.ECR_URL }}/reactjs-app
