name: CI/CD

on:
  push:
    branches:
      - new-deploy

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      # Removed Docker Hub login step
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ECR_URL }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build Docker Image
        run: docker build -t 551347377649.dkr.ecr.us-east-1.amazonaws.com/react-ci-cd  ./server
      - name: Push Image to ECR
        run: docker push 551347377649.dkr.ecr.us-east-1.amazonaws.com/react-ci-cd:latest

  deploy_bakend:
    needs: build_backend
    runs-on: self-hosted
    steps:
      # Consider pre-building and deploying images from ECR for security reasons
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ECR_URL }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Pull image from ECR (Optional)
        run: docker pull 551347377649.dkr.ecr.us-east-1.amazonaws.com/react-ci-cd:latest  # Remove if using pre-built images
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name nodejs-app-container -e MONGODB_URI='${{ secrets.MONGODB_URI }}' 551347377649.dkr.ecr.us-east-1.amazonaws.com/react-ci-cd:latest

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ECR_URL }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # Removed Docker Hub login step
      - name: Build Docker Image
        run: docker build -t 551347377649.dkr.ecr.us-east-1.amazonaws.com/react-ci-cd --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL }}'  ./client
      - name: Push Image to ECR
        run: docker push 551347377649.dkr.ecr.us-east-1.amazonaws.com/react-ci-cd:latest

  deploy_frontend:
    needs: build_frontend
    runs-on: self-hosted
    steps:
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ECR_URL }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Pull image from ECR (Optional)
        run: docker pull 551347377649.dkr.ecr.us-east-1.amazonaws.com/react-ci-cd:latest  # Remove if using pre-built images
      - name: Delete old container
        run: docker rm -f reactjs-app-container
      - name: Run Docker Container
        run: docker run -d -p 80:80 --name reactjs-app-container 551347377649.dkr.ecr.us-east-1.amazonaws.com/react-ci-cd:latest
