name: CI/CD

on:
  push:
    paths:
      - 'server/**'
      - 'client/**'

jobs:
  build_backend:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event_path == 'server'
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t rushi173/nodejs-app  ./server
      - name: Publish Image to docker hub
        run: docker push rushi173/nodejs-app:latest 
 
  deploy_bakend:
    needs: build_backend
    runs-on: self-hosted 
    if: github.event_name == 'push' && github.event_path == 'server'
    steps:
      - name: Pull image from docker hub
        run: docker pull rushi173/nodejs-app:latest 
      - name: Delete old container
        run: docker rm -f nodejs-app-container  
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name nodejs-app-container -e MONGODB_URI='${{ secrets.MONGODB_URI }}' rushi173/nodejs-app
